services:
  web:
    build: 
      context: api-dev/
    ports:
      - "8081:80"

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db4dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: db4dev$
    ports:
      - "4000:80"
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
